name: Apply Terraform changes

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ vars.GOOGLE_CREDENTIALS }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.0

    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ vars.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Write Google credentials to file
      run: |
          echo '${{ vars.GOOGLE_CREDENTIALS }}' > gcp-key.json
          cat gcp-key.json

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: |
        terraform plan \
          -var="google_credentials=./gcp-key.json" \
          -var="project=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"

    - name: Apply Terraform changes
      if: github.ref == 'refs/heads/main'
      run: |
        terraform apply \
          -var="google_credentials=./gcp-key.json" \
          -var="project=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}" \
          -auto-approve
